Homework-Assignment-React-Tech-It-Easy
mjerta/frontend-react-tech-it-easy pull request #1
Opened 2024-07-12 14:16 UTC by mjerta

- **Add Opdracht 1 - Helperfuncties**
- **Added result from opdracht 2**
- **Add all styling**
- **Refactor names and exports**
- **Forgot to refactor the name of nameOfTelevision**
- **Remove all imports from helper functions**
- **Refactor some helper names to more general names so they could be used more generally in the future**
- **Add buttons with an console log**
- **Remove index.css that is not neeeded**
- **Clean code in the App.css**

2024-08-30 21:48 UTC, smallproject commented
Hey Maarten,

Ik heb wat meegekeken. In het algemeen het ziet wel goed uit.

Ik heb er weinig toe te voegen.

Goed bezig

2024-09-27 09:57 UTC, S-Barnhoorn requested changes
Goed bezig Maarten! Je bent ook goed jezelf aan het uitdagen en aan het experimenteren.

Let wel op de naming conventions van files. Components en Pages dienen altijd te beginnen met een hoofdletter. Voor helper functies of andere niet component files mag je kleine letters gebruiken.

2024-09-27 09:57 UTC, S-Barnhoorn commented on src/App.jsx
> +    const result = [...inventory].sort(sortImplements[sortkey].sortFunction)
Leuk gedaan!

2024-09-27 09:57 UTC, S-Barnhoorn commented on src/App.jsx
> +  const [sortedInventory, setSortedInventory] = useState(inventory);
Nu al begonnen met state! Lekker bezig hoor.

2024-09-27 09:57 UTC, S-Barnhoorn commented on src/components/box.jsx
> +Box.propTypes = {
propTypes is niet persé noodzakelijk omdat de data allemaal intern binnen de applicatie zit. Wanneer de data vanuit een API naar binnen wordt gehaald is het gebruik van propTypes wel interessant omdat je zo mogelijke problemen kan opvangen wanneer bijvoorbeeld de data die je uit de API haalt is veranderd.

2024-11-20 21:34 UTC, merged